sonar.projectKey=washify-car-wash
sonar.projectName=Washify Car Wash Service
sonar.sources=.
sonar.language=py
sonar.python.version=3
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/venv/**,**/.env,**/node_modules/**
sonar.sourceEncoding=UTF-8
